---
- name: Find optional RPM repos  # noqa: command-instead-of-module risky-shell-pipe
  ansible.builtin.shell:
    cmd: |
      yum repolist disabled |grep codeready_builder |cut -d ' ' -f 1 |cut -d / -f 1
  changed_when: false
  check_mode: false  # This is read-ony and ok to run in check mode
  register: res
  tags: packages

- name: Enable optional RPMs in Yum
  ansible.builtin.command: yum-config-manager --enable {{ item }}
  with_items: "{{ res.stdout_lines }}"
  changed_when: res.stdout_lines | length > 0
  tags: packages

- name: Add EPEL repository
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    disable_gpg_check: true
  when: extra_os_repos_enable_epel
  tags: packages
