---
rdbms_install_versions:
  12.2.0.1: &v12201
    short_ver: "12.2.0"
    installer_wd_suffix: /database
    installer_creates: oraInst.loc
    success_stdout: Successfully Setup
    extra_args: "-showProgress"
    oraparam_path: install/oraparam.ini

  client_12.2.0.1:
    <<: *v12201
    installer_wd_suffix: /client
    extra_args: "-noconfig -force -showProgress"
    oracle_home_name: "client_1"

  19.0.0:
    short_ver: "19.0.0"
    zip_creates: install/.img.bin
    installer_creates: oraInst.loc
    success_stdout: Successfully Setup
    assume_distid:
      default:
        "8": OEL8
        "9": OL8

  19.3.0:
    short_ver: "19.3.0"
    zip_creates: install/.img.bin
    installer_creates: oraInst.loc
    success_stdout: Successfully Setup
    assume_distid:
      default:
        "8": OEL8
        "9": OEL8

  client_19.3.0:
    short_ver: "19.3.0"
    zip_name: LINUX.X64_193000_client_home.zip
    zip_creates: instantclient/libclntshcore.so.19.1
    installer_creates: oraInst.loc
    extra_args: "-noconfig"
    oracle_home_name: "client_1"
    success_stdout: Successfully Setup
    assume_distid:
      default:
        "8": OEL8
        "9": OL8

rdbms_install__: "{{ rdbms_install_versions[rdbms_install_version] }}"
rdbms_install_use_zip: "{{ rdbms_install__.zip_creates is defined }}"
rdbms_install_zip_creates: "{{ rdbms_install__.zip_creates }}"
rdbms_install_short_ver: "{{ rdbms_install__.short_ver }}"

rdbms_install_oracle_home_name: >-
  {{ rdbms_install__.oracle_home_name | d('dbhome_1') }}

rdbms_install_oracle_home: >-
  {{ oracle_product_dir }}/{{ rdbms_install_short_ver }}/{{ rdbms_install_oracle_home_name }}

rdbms_install_resp_dir: "{{ oracle_base }}/resp"
rdbms_install_resp_file: "{{ rdbms_install_resp_dir }}/{{ rdbms_install_version }}.rsp"
rdbms_install_installer_name: "rdbms-{{ rdbms_install_version }}-linux-x64"

rdbms_install_zip_name: >-
  {{ rdbms_install__.zip_name
  | d('rdbms-' + rdbms_install_version + '-linux-x64.zip') }}

rdbms_install_installer: >-
  {{ stage_dir }}/database/{{ rdbms_install_use_zip
    | ternary(rdbms_install_zip_name, rdbms_install_installer_name) }}

rdbms_install_installer_creates: >-
  {{ rdbms_install_oracle_home }}/{{ rdbms_install__.installer_creates }}

rdbms_install_installer_wd: >-
  {{ rdbms_install_use_zip | ternary(rdbms_install_oracle_home, rdbms_install_installer)
     + rdbms_install__.installer_wd_suffix | d('') }}

rdbms_install_oraparam_path: >-
  {{ rdbms_install_installer_wd }}/{{
     rdbms_install__.oraparam_path | d('oui/oraparam.ini') }}

rdbms_install_debug_enabled: false
rdbms_install_debug_opt: "{{ '-debug' if rdbms_install_debug_enabled else '' }}"

rdbms_install_command_prepend: ""

rdbms_install_command: >-
  {{ rdbms_install_command_prepend }} ./runInstaller
  -silent
  -waitforcompletion
  -responseFile {{ rdbms_install_resp_file }}
  {{ rdbms_install_debug_opt }}
  {{ rdbms_install__.extra_args | d('') }}

rdbms_install_success_stdout: "{{ rdbms_install__.success_stdout }}"
rdbms_install_lsnrctl_path: "{{ rdbms_install_oracle_home }}/bin/lsnrctl"
rdbms_install_oraenv_path: /usr/local/bin/oraenv

rdbms_install__adi: "{{ rdbms_install__.assume_distid | d({}) }}"
rdbms_install__adi_d: >-
  {{ rdbms_install__adi[ansible_distribution]
     | d(rdbms_install__adi[ansible_os_family])
     | d(rdbms_install__adi['default'])
     | d({}) }}

rdbms_install_assume_distid: >-
  {{ rdbms_install__adi_d[ansible_distribution_major_version]
     | d(rdbms_install__adi_d['default'])
     | d(omit) }}

rdbms_install_root_scripts:
  - script: "{{ oracle_inv_dir }}/orainstRoot.sh"
    creates: /etc/oraInst.loc
  - script: "{{ rdbms_install_oracle_home }}/root.sh"
    creates: /etc/oratab

rdbms_install_hugepages_enabled: false
rdbms_install_disable_swap_requirement: false
