---
namespace: "sigcorp"
name: "core"
version: 1.0.0
readme: README.md
authors:
  - Dan Boitnott <boitnott@sigcorp.com>

description: Core roles for SIG services
license_file: LICENSE

tags: ["linux", "tools"]
dependencies: {}

repository: https://github.com/sig-ansible/sig-ansible-core
documentation: https://github.com/sig-ansible/sig-ansible-core
homepage: https://github.com/sig-ansible/sig-ansible-core
issues: https://github.com/sig-ansible/sig-ansible-core/issues

build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
