---
- name: Converge
  hosts: all
  vars_files:
    - vars/tests.yml

  tasks:
    - name: "Compute role spec"
      ansible.builtin.set_fact:
        molecule_test_spec: >-
          {{ {'role': 'sigcorp.core.' + molecule_test_name }
             | combine(molecule_tests[molecule_test_name]) }}

    - name: "Set test vars"
      ansible.builtin.set_fact:
        "{{ item.key }}": "{{ item.value }}"  # noqa: var-naming[no-jinja]
      loop: "{{ molecule_test_spec.vars | default({}) | dict2items }}"

    - name: "Dump Test Info"
      ansible.builtin.debug:
        msg:
          role: "{{ molecule_test_spec.role }}"
          vars: "{{ molecule_test_spec.vars | default({}) }}"

    - name: "Apply the role"
      ansible.builtin.include_role:
        name: "{{ molecule_test_spec.role }}"
