---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

platforms:
  - name: molecule-rhel-8
    image: redhat/ubi8
  - name: molecule-rhel-9
    image: redhat/ubi9
  - name: molecule-oracle-8
    image: oraclelinux:8
  - name: molecule-oracle-9
    image: oraclelinux:9
