---
molecule_tests:
  about:
  extra_os_repos:

  has_oracle:
    vars:
      oracle_gid: 901
      oracle_uid: 901
      oracle_os_groups:
        oinstall: 912
        dba: 913
        oper: 914
      tnsnames_entries:
        - sid: FAKE
          host: not.real

  jobsub_users:
    vars:
      jobsub_banner_group: banner
      jobsub_banner_group_gid: 921
      jobsub_banner_user: banner
      jobsub_banner_user_uid: 921
      jobsub_gurjobs_user: banjobs
      jobsub_gurjobs_user_uid: 931
      jobsub_gurjobs_group: gurjobs
      jobsub_gurjobs_group_gid: 932
      jobsub_cleanaddress_enabled: true
      jobsub_cleanaddress_user: cleanddr
      jobsub_cleanaddress_user_uid: 941
      jobsub_cleanaddress_group: ca
      jobsub_cleanaddress_group_gid: 942
      jobsub_oracle_in_banner_group: true
      oracle_user: oracle
      jobsub_site_users:
        - name: someguy
          uid: 1111
          groups:
            - wheel

  login_banner:
    vars:
      login_banner_text: Molecule

  openjdk_8:
    role: sigcorp.core.openjdk
    vars:
      openjdk_major_version: 8
  openjdk_11:
    role: sigcorp.core.openjdk
    vars:
      openjdk_major_version: 11

  package_specs-empty:
    role: sigcorp.core.package_specs
    vars:
      package_specs: []

  package_specs-all-specs:
    role: sigcorp.core.package_specs
    vars:
      package_specs:
        - name: bash
        - name: fail_family
          family:
            RedHat: bash
            default: bash
        - name: bad_distro
          distro:
            RedHat: bash
            default: bash

  rdbms_install-12201:
    role: sigcorp.core.rdbms_install
    stage:
      ## TODO Switch this to something authenticated before release
      - url: "http://m.oiu.tv/p1dCfU3T8p/oracle/rdbms/rdbms-12.2.0.1.0-linux-x86-64/RDMBS-Enterprise-12c-12.2.0.1.0-Linux-x64.zip"  # noqa: yaml[line-length]
        dest: "database/rdbms-12.2.0.1-linux-x64/RDMBS-Enterprise-12c-12.2.0.1.0-Linux-x64.zip"
        checksum: "sha1:12598250be536c9d074ae0eb2f7df4a9b463d0eb"
        unarchive:
          creates: "database/runInstaller"
    vars: &rdbms_install-defaults
      rdbms_install_version: 12.2.0.1
      oracle_base: /u01/app/oracle
      oracle_inv_dir: /u01/app/oraInventory
      oracle_product_dir: /u01/app/oracle/product
      oracle_uid: 811
      oracle_gid: 811
      oracle_os_groups:
        oinstall: 821
        dba: 831
      stage_dir: /mnt/stage
      tnsnames_entries:
        - sid: FAKE
          host: db.fake.xyz

  rdbms_install-client_12201:
    role: sigcorp.core.rdbms_install
    stage:
      ## TODO Switch this to something authenticated before release
      - url: http://m.oiu.tv/p1dCfU3T8p/oracle/rdbms_client/oracle_db_client_linux_amd64_12201.zip
        dest: "database/rdbms-client_12.2.0.1-linux-x64/oracle_db_client_linux_amd64_12201.zip"
        checksum: "sha1:49a798b357c87d07b8ff51679fa051fc317e2246"
        unarchive:
          creates: "database/runInstaller"
    vars:
      <<: *rdbms_install-defaults
      rdbms_install_version: client_12.2.0.1

  rdbms_install-1900:
    role: sigcorp.core.rdbms_install
    vars:
      <<: *rdbms_install-defaults
      rdbms_install_version: 19.0.0
    stage:
      ## TODO Switch this to something authenticated before release
      - url: http://m.oiu.tv/p1dCfU3T8p/oracle/rdbms/rdbms-19.0.0-linux-x86-64/rdbms-19.0.0-linux-x64.zip  # noqa: yaml[line-length]
        dest: "database/rdbms-19.0.0-linux-x64.zip"
        checksum: "sha1:1f3aceffb3821464ed46e73a821cf07e5d2686e6"

  rdbms_install-client_1930:
    role: sigcorp.core.rdbms_install
    vars:
      <<: *rdbms_install-defaults
      rdbms_install_version: client_19.3.0
    stage:
      ## TODO Switch this to something authenticated before release
      - url: https://s3.amazonaws.com/m.oiu.tv/p1dCfU3T8p/oracle/rdbms_client/LINUX.X64_193000_client_home.zip  # noqa: yaml[line-length]
        dest: "database/LINUX.X64_193000_client_home.zip"
        # checksum: "sha1:49a798b357c87d07b8ff51679fa051fc317e2246"

  rngd:
  shell_utils:
  skiring:

  # Can't test in containers (yet)
  # disable_firewall:
  # hugepages:
  # permissive_logrotate:
