---
molecule_tests:
  about:
  extra_os_repos:

  has_oracle:
    vars:
      oracle_gid: 901
      oracle_uid: 901
      oracle_os_groups:
        oinstall: 912
        dba: 913
        oper: 914
      tnsnames_entries:
        - sid: FAKE
          host: not.real

  jobsub_users:
    vars:
      jobsub_banner_group: banner
      jobsub_banner_group_gid: 921
      jobsub_banner_user: banner
      jobsub_banner_user_uid: 921
      jobsub_gurjobs_user: banjobs
      jobsub_gurjobs_user_uid: 931
      jobsub_gurjobs_group: gurjobs
      jobsub_gurjobs_group_gid: 932
      jobsub_cleanaddress_enabled: true
      jobsub_cleanaddress_user: cleanddr
      jobsub_cleanaddress_user_uid: 941
      jobsub_cleanaddress_group: ca
      jobsub_cleanaddress_group_gid: 942
      jobsub_oracle_in_banner_group: true
      oracle_user: oracle
      jobsub_site_users:
        - name: someguy
          uid: 1111
          groups:
            - wheel

  login_banner:
    vars:
      login_banner_text: Molecule

  openjdk_8:
    role: sigcorp.core.openjdk
    vars:
      openjdk_major_version: 8
  openjdk_11:
    role: sigcorp.core.openjdk
    vars:
      openjdk_major_version: 11

  package_specs-empty:
    role: sigcorp.core.package_specs
    vars:
      package_specs: []

  package_specs-all-specs:
    role: sigcorp.core.package_specs
    vars:
      package_specs:
        - name: bash
        - name: fail_family
          family:
            RedHat: bash
            default: bash
        - name: bad_distro
          distro:
            RedHat: bash
            default: bash

  rngd:
  shell_utils:
  skiring:

  # Can't test in containers (yet)
  # disable_firewall:
  # hugepages:
  # permissive_logrotate:
