---
molecule_tests:
  about:
  extra_os_repos:

  has_oracle:
    vars:
      oracle_gid: 901
      oracle_uid: 901
      oracle_os_groups:
        oinstall: 912
        dba: 913
        oper: 914
      tnsnames_entries:
        - sid: FAKE
          host: not.real

  login_banner:
    vars:
      login_banner_text: Molecule

  openjdk_8:
    role: sigcorp.core.openjdk
    vars:
      openjdk_major_version: 8
  openjdk_11:
    role: sigcorp.core.openjdk
    vars:
      openjdk_major_version: 11

  package_specs-empty:
    role: sigcorp.core.package_specs
    vars:
      package_specs: []

  package_specs-all-specs:
    role: sigcorp.core.package_specs
    vars:
      package_specs:
        - name: bash
        - name: fail_family
          family:
            RedHat: bash
            default: bash
        - name: bad_distro
          distro:
            RedHat: bash
            default: bash

  rngd:
  shell_utils:
  skiring:

  # Can't test in containers (yet)
  # disable_firewall:
  # hugepages:
  # permissive_logrotate:
